server:
  port:
    8082

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    hibernate.generate-ddl-auto: true
    properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.format_sql: true
    